### ISSUE TITLE
core-overlay resizeHandler when mobile keyboard appears

### ISSUE THREAD

**Issue by nomego** [Polymer/core-overlay#41]
I'm using a `paper-action-dialog` with input fields.
When using the app on mobile, opening the dialog and focusing in an input field brings up the on-screen keyboard, which compresses the dialog while "trying" to keep the original positioning.

It does trigger a resize-event (calling resizeHandler) but I suspect that it fires too early and the resizeHandler gets the wrong dimensions for calculating the new size.

Flipping the phone to landscape and back to portrait properly resizes the core-overlay, though.

JSBin at http://jsbin.com/teragoxibu/2

Opening a dialog with input:

![mobile-overlay-input-1](https://cloud.githubusercontent.com/assets/960553/5409012/aa417e62-81e4-11e4-9a63-dde01d393716.png)

Focus in an input:

![mobile-overlay-input-2](https://cloud.githubusercontent.com/assets/960553/5409013/aec629a6-81e4-11e4-8fe5-f9874d0e5ea7.png)

Flip phone landscale and back again:

![mobile-overlay-input-3](https://cloud.githubusercontent.com/assets/960553/5409015/b261af5e-81e4-11e4-8833-c8fe1552c988.png)

**Comment by schnie** [comment]
Also having this issue. @nomego did you find any way around this?

**Comment by marcus7777** [comment]
:+1: me too

**Comment by joaovieira** [comment]
+1

**Comment by ronnyroeller** [comment]
This problem seems to be as well in iron-overlay (Polymer 1.0).

**Comment by phanikiranwtc** [comment]
+1

**Comment by prakash1517** [comment]
:disappointed: me too 
any help  ???

**Comment by nomego** [comment]
Actually I can't reproduce this with latest Polymer and `paper-dialog`.
